# Generated by Django 3.0.8 on 2022-05-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweb', '0003_auto_20220506_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to='blogImages'),
        ),
    ]
