# Generated by Django 3.0.8 on 2022-06-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweb', '0005_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='initials',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
